name: Deployments of Microservices

env:
  SERVICE_NAME_SERVER: "app-server"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - staging
      
  workflow_dispatch:

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}-servers-deploy
  cancel-in-progress: true
  
jobs:  



  dockerize-and-deploy-server:
    # needs: lint - if have linting job
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' || github.event_name == 'workflow_dispatch' 
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 🔍 Check changes in Server Directory
        id: server-changed
        shell: bash
        # checking directory changes with git
        run: |
            echo "server_changed=false" >> "$GITHUB_OUTPUT"
            echo "dockerfile_changed=false" >> "$GITHUB_OUTPUT"
        
            BASE_SHA="${{ github.event.pull_request.base.sha || github.event.before }}"
            HEAD_SHA="${{ github.sha }}"
        
            if git diff --quiet "$BASE_SHA" "$HEAD_SHA" -- ./apps/server; then
              echo "No server changes"
            else
              echo "server_changed=true" >> "$GITHUB_OUTPUT"
            fi
        
            if git diff --quiet "$BASE_SHA" "$HEAD_SHA" -- ./apps/server/Dockerfile; then
              echo "No Dockerfile changes"
            else
              echo "dockerfile_changed=true" >> "$GITHUB_OUTPUT"
            fi

      - name: 🔑 Set up Google Cloud Auth SDK
        if: steps.server-changed.outputs.server_changed == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}
            

      
      - name: ⚙️ Log in Docker to GCR
        if: steps.server-changed.outputs.server_changed == 'true'
        uses: docker/login-action@v2
        with:
            registry: gcr.io
            username: _json_key
            password:  ${{ secrets.CREDENTIALS_JSON }}
      
      - name: 🐳 Build and Push Docker Image
        if:  steps.server-changed.outputs.dockerfile_changed == 'true'
        run: |
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME_SERVER }}:latest"
          docker build --pull --rm -f "apps/server/Dockerfile" -t "${IMAGE_NAME}" "apps/server"
          docker push "${IMAGE_NAME}"

      - name: 🚀 Deploy to Cloud Run 
        if: success()
        run: |  
          IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.SERVICE_NAME_SERVER }}:latest"
          gcloud run deploy ${{ env.SERVICE_NAME_SERVER }} \
            --image "${IMAGE_NAME}" \
            --platform managed \
            --region ${{ secrets.GCP_PROJECT_REGION }} \
            --allow-unauthenticated

