name: Deploy to Vercel - Server

on:
  push:
    branches:
      - main
    paths:
      - 'apps/server/**'  # Only trigger if changes in this directory
  pull_request:
    branches:
      - main
    paths:
      - 'apps/server/**'  # Only trigger if changes in this directory
  workflow_dispatch: 

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_CE_SERVER }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # Set default working directory for all steps
    defaults:
      run:
        working-directory: apps/server
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build for dist folder
        run: bun run build

      - name: Run tests (optional)
        run: bun test
        continue-on-error: true  # Remove this if you want tests to block deployment

      - name: Install Vercel CLI
        run: bun install --global vercel@latest
        working-directory: .

      - name: Deploy to Vercel (Production)
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel (Preview)
        if: github.event_name == 'pull_request'
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
