name: ðŸš€ Deployments of Microservices

env:
  SERVICE_NAME_SERVER: "college-ecosystem-server"

# on: workflow_dispatch

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  #     - staging
      
  workflow_dispatch:

concurrency:
  group:  ${{ github.workflow }}-${{ github.ref }}-servers-deploy
  cancel-in-progress: true
  
jobs:  



  dockerize-and-deploy-server:
    # needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging' || github.event_name == 'workflow_dispatch' 
    steps:
      - name: ðŸ“¥ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: ðŸ” Check changes in Server Directory
        id: server-changed
        shell: bash
        run: |
            echo "server_changed=false" >> "$GITHUB_OUTPUT"
            echo "dockerfile_changed=false" >> "$GITHUB_OUTPUT"
        
            BASE_SHA="${{ github.event.pull_request.base.sha || github.event.before }}"
            HEAD_SHA="${{ github.sha }}"
        
            if git diff --quiet "$BASE_SHA" "$HEAD_SHA" -- ./apps/server; then
              echo "No server changes"
            else
              echo "server_changed=true" >> "$GITHUB_OUTPUT"
            fi
        
            if git diff --quiet "$BASE_SHA" "$HEAD_SHA" -- ./apps/server/Dockerfile; then
              echo "No Dockerfile changes"
            else
              echo "dockerfile_changed=true" >> "$GITHUB_OUTPUT"
            fi

      - name: ðŸ”‘ Set up Google Cloud Auth SDK
        if: steps.server-changed.outputs.server_changed == 'true'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}
            
      - name: ðŸš€ Deploy to Cloud Run (from source, no Artifact Registry)
        if: steps.server-changed.outputs.server_changed == 'true'
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME_SERVER }} \
            --source ./apps/server \
            --region ${{ secrets.GCP_PROJECT_REGION }} \
            --platform managed \
            --allow-unauthenticated
